language: node_js
node_js:
  - "7"
before_install:
  - npm install gitbook-cli -g
jobs:
  include:
    - stage: compile
      script: ./ci.sh compile
    - stage: deploy
      script: ./ci.sh deploy
stages:
  - compile
  - name: deploy
    if: type NOT IN (pull_request)